version: '3'
services:
  blog:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_URL=jdbc:postgresql://localhost:5432/blog
    ports:
      - "3007:3007"
    restart: always
  database:
    image: postgres:latest
    environment:
      - POSTGRES_USER=blog
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=blog
    volumes:
      - database:/var/lib/postgresql/data
    restart: always
    ports:
      - "5432:5432"
volumes:
  database: